version: "3.8"

services:
  asf-backend:
    build: ./ASFbackend
    container_name: asf-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://172.22.121.2:11434

  frontend:
    build:
      context: ./frontend_ASF
      dockerfile: Dockerfile
    container_name: asf-frontend
    ports:
      - "8089:80"
    networks:
      - apn-network

  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - 11434:11434

networks:
  apn-network:
    driver: bridge
