version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asf-frontend
    ports:
      - "8089:80"
    networks:
      - apn-network

  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - 11434:11434

networks:
  apn-network:
    driver: bridge
