version: '3.8'

services:

  mysql-db:
    # 指定容器的名称
    container_name: ASF-mysql     
    # 指定镜像和版本
    image: mysql:8.0                   
    ports:
      - "3306:3306"
    restart: always
    # 容器日志大小配置
    logging:
      driver: 'json-file'
      options:
        max-size: '5g'
    environment:
      # 配置root密码
      MYSQL_ROOT_PASSWORD: Www028820
    volumes:
      # 挂载数据目录到当前目录下的 mysql/data
      - "./data:/var/lib/mysql"
      # 挂载初始化脚本目录
      - "./init:/docker-entrypoint-initdb.d"
      # 挂载配置文件目录到当前目录下的 mysql/config
      - "./config:/etc/mysql/conf.d" 
